import { useEffect, useState } from "react";
import { useParams } from "wouter";
import { format, parseISO } from "date-fns";
import { BookOpen, Loader2, AlertTriangle, GraduationCap, Building2, Calendar, Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

interface Profile {
  fullName: string;
  school: string;
  course: string;
  siwesCompany: string;
  department: string;
  siwesDuration: string;
}

interface Entry {
  id: number;
  date: string;
  dayOfWeek: string | null;
  week: number | null;
  rewrittenEntry: string | null;
  rawActivity: string;
}

export default function SupervisorPortal() {
  const params = useParams<{ token: string }>();
  const token = params.token;

  const [profile, setProfile] = useState<Profile | null>(null);
  const [entries, setEntries] = useState<Entry[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!token) return;
    const apiUrl = import.meta.env.VITE_API_URL;
    fetch(`${apiUrl}/api/supervisor/${token}`)
      .then(async (res) => {
        if (!res.ok) {
          const err = await res.json();
          throw new Error(err.error || "Logbook not found");
        }
        return res.json();
      })
      .then((data) => {
        setProfile(data.profile);
        setEntries(data.entries);
      })
      .catch((err) => setError(err.message))
      .finally(() => setLoading(false));
  }, [token]);

  // Group entries by week
  const groupedByWeek = entries.reduce((acc, entry) => {
    const key = entry.week ? `Week ${entry.week}` : "Unassigned";
    if (!acc[key]) acc[key] = [];
    acc[key].push(entry);
    return acc;
  }, {} as Record<string, Entry[]>);

  const handlePrint = () => window.print();

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <Loader2 className="h-8 w-8 animate-spin text-primary/50" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen gap-4 px-4 text-center">
        <AlertTriangle className="h-12 w-12 text-amber-500" />
        <h1 className="text-2xl font-bold">Logbook not found</h1>
        <p className="text-muted-foreground max-w-sm">{error}</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50 print:bg-white">
      {/* Header */}
      <header className="bg-white border-b sticky top-0 z-10 print:static">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2 text-primary font-bold text-xl">
            <BookOpen className="h-6 w-6" />
            <span>AcademiQ</span>
          </div>
          <div className="flex items-center gap-3 print:hidden">
            <span className="text-xs text-muted-foreground bg-amber-50 border border-amber-200 px-3 py-1 rounded-full font-medium text-amber-700">
              Supervisor View — Read Only
            </span>
            <Button variant="outline" size="sm" onClick={handlePrint} className="gap-2">
              <Download className="h-4 w-4" /> Print / Save PDF
            </Button>
          </div>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-6 py-8 flex flex-col gap-8">
        {/* Student info */}
        <div className="bg-white rounded-2xl border shadow-sm overflow-hidden">
          <div className="bg-primary/5 border-b px-6 py-4">
            <h1 className="text-2xl font-bold">{profile?.fullName || "Student"}'s SIWES Logbook</h1>
            <p className="text-muted-foreground text-sm mt-1">{entries.length} entries · Generated by AcademiQ</p>
          </div>
          <div className="grid sm:grid-cols-2 gap-4 p-6">
            <div className="flex items-start gap-3">
              <GraduationCap className="h-5 w-5 text-primary shrink-0 mt-0.5" />
              <div>
                <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Academic</p>
                <p className="font-semibold">{profile?.school || "—"}</p>
                <p className="text-sm text-muted-foreground">{profile?.course || "—"}</p>
              </div>
            </div>
            <div className="flex items-start gap-3">
              <Building2 className="h-5 w-5 text-primary shrink-0 mt-0.5" />
              <div>
                <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Placement</p>
                <p className="font-semibold">{profile?.siwesCompany || "—"}</p>
                <p className="text-sm text-muted-foreground">{profile?.department || "—"}</p>
              </div>
            </div>
            {profile?.siwesDuration && (
              <div className="flex items-start gap-3">
                <Calendar className="h-5 w-5 text-primary shrink-0 mt-0.5" />
                <div>
                  <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Duration</p>
                  <p className="font-semibold">{profile.siwesDuration}</p>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Entries grouped by week */}
        {Object.entries(groupedByWeek).map(([weekLabel, weekEntries]) => (
          <div key={weekLabel} className="flex flex-col gap-3">
            <div className="flex items-center gap-3">
              <h2 className="text-lg font-bold">{weekLabel}</h2>
              <span className="text-xs text-muted-foreground bg-muted px-2 py-0.5 rounded-full">
                {weekEntries.length} {weekEntries.length === 1 ? "entry" : "entries"}
              </span>
            </div>
            <div className="space-y-3">
              {weekEntries.map((entry) => (
                <Card key={entry.id} className="border-muted/60 shadow-sm">
                  <CardContent className="p-5">
                    <div className="flex items-center gap-3 mb-3">
                      <div className="shrink-0 flex flex-col items-center justify-center bg-primary/5 rounded-lg p-2 min-w-[64px] border border-primary/10">
                        <span className="text-xs font-medium text-muted-foreground uppercase">{format(parseISO(entry.date), "MMM")}</span>
                        <span className="text-xl font-bold text-primary font-serif">{format(parseISO(entry.date), "dd")}</span>
                      </div>
                      <div>
                        <p className="font-semibold">{entry.dayOfWeek || format(parseISO(entry.date), "EEEE")}</p>
                        <p className="text-xs text-muted-foreground">{format(parseISO(entry.date), "MMMM d, yyyy")}</p>
                      </div>
                    </div>
                    <div className="bg-muted/20 rounded-xl p-4 text-sm leading-relaxed font-serif border border-muted/30">
                      {entry.rewrittenEntry || entry.rawActivity}
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        ))}

        {entries.length === 0 && (
          <div className="text-center py-16 bg-white rounded-2xl border border-dashed border-muted">
            <BookOpen className="h-10 w-10 text-muted-foreground/30 mx-auto mb-3" />
            <p className="text-muted-foreground">No entries have been written yet.</p>
          </div>
        )}

        <p className="text-center text-xs text-muted-foreground pb-4">
          This logbook was shared via AcademiQ — AI-powered SIWES logbook for Nigerian students.
        </p>
      </main>
    </div>
  );
}
